import { useCallback, useEffect, useMemo, useState, type CSSProperties, type ReactNode } from "react";

type RiskLevel = "LOW" | "MEDIUM" | "HIGH";
type CaseStatus = "OPEN" | "IN_REVIEW" | "ESCALATED" | "CLEARED" | "CLOSED";
type CasePriority = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
type Disposition = "NONE" | "CLEARED" | "SUSPICIOUS" | "ESCALATED";
type Evidence = { evidence_id: string; title: string; severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO"; category: string; facts: Record<string, unknown> };
type Behavior = { history_available: boolean; availability_explanation: string; prior_transaction_count: number; prior_total_amount: number; prior_amount: { average: number; median: number; maximum: number } | null; current_amount_context: { amount_vs_prior_average: number | null; prior_empirical_percentile: number; exceeds_prior_maximum: boolean } | null; recent_activity: { steps_since_previous_transaction: number | null }; transaction_type_context: { is_new_transaction_type_for_origin: boolean } };
type Relationship = { context_available: boolean; history_available: boolean; availability_explanation: string; relationship_seen_before: boolean | null; prior_interaction_count: number; prior_total_amount: number; prior_amount: { average: number; median: number; maximum: number } | null; current_amount_context: { amount_vs_prior_average: number | null; prior_empirical_percentile: number; exceeds_prior_relationship_maximum: boolean } | null; steps_since_previous_interaction: number | null; baseline_is_limited: boolean; origin_network: { prior_unique_counterparty_count: number; current_destination_is_new: boolean | null }; destination_network: { prior_unique_origin_count: number; current_origin_is_new_for_destination: boolean | null } };
type CaseSummary = { case_id: string; status: CaseStatus; priority: CasePriority; created_at: string; updated_at: string; source_type: "REFERENCE" | "MANUAL"; transaction_reference_available: boolean; model_version: string; fraud_probability: number; risk_level: RiskLevel; operating_mode: "BALANCED"; evidence_summary: { total_count: number; highest_severity: string | null }; analyst_decision: { disposition: Disposition; note: string | null; disposition_at: string | null; is_model_ground_truth: false } };
type Copilot = { provider: string; mode: "real_llm" | "deterministic_fallback"; ai_available: boolean; model: string | null; fallback_reason: string | null; execution?: { generated_by: "real_provider" | "deterministic_fallback"; provider_attempted: boolean; provider_succeeded: boolean; generation_latency_ms: number | null; failure_category: string | null } | null; report: { summary: string; risk_assessment: { level: RiskLevel; assessment: string }; key_signals: { signal: string; importance: string; explanation: string; evidence_ids: string[] }[]; behavioral_analysis: { summary: string; history_limitation: string | null }; relationship_analysis: { summary: string; history_limitation: string | null }; uncertainties: string[]; recommended_actions: { action: string; reason: string }[]; disclaimer: string } };
type DecisionTrace = { event: string; occurred_at: string; actor: "SYSTEM" | "COPILOT" | "ANALYST"; label: string; detail: string; previous_status: CaseStatus | null; new_status: CaseStatus | null; copilot_mode: "real_llm" | "deterministic_fallback" | null; note_recorded: boolean };
type CaseDetail = { case: CaseSummary; intelligence_snapshot: { transaction: { transaction_type: string; amount: number; origin_balance_before: number; hour_of_day: number }; model_output: { fraud_probability: number; risk_score: number; risk_level: RiskLevel; fraud_prediction: boolean; classification_threshold: number; operating_mode: "BALANCED"; recommended_simulated_action: string }; evidence: Evidence[]; behavioral_context: Behavior; relationship_context: Relationship }; investigation_limitations: string[]; copilot: Copilot | null; status_history: { occurred_at: string; previous_status: CaseStatus | null; new_status: CaseStatus; disposition: Disposition; note_recorded: boolean }[]; decision_trace: DecisionTrace[]; snapshot_is_immutable: true };
type CaseList = { items: CaseSummary[]; total: number; limit: number; offset: number };
type ApiError = { detail?: string | { msg?: string }[] };
type ReadinessComponent = { key: string; label: string; status: "ready" | "unavailable"; version: string | null; mode: string | null; fallback_available: boolean; provider_enabled?: boolean | null; provider_configured?: boolean | null; external_availability?: "not_checked" | "not_applicable" | null; message: string };
type SystemReadiness = { status: "ready" | "degraded"; components: ReadinessComponent[]; advisory_only: true };
type OperationalMetrics = { total_cases: number; active_cases: number; status_counts: { open: number; in_review: number; escalated: number; cleared: number; closed: number }; priority_counts: { critical: number; high: number; medium: number; low: number }; disposition_counts: { none: number; cleared: number; suspicious: number; escalated: number }; copilot_reports: { total: number; deterministic_fallback: number; real_llm: number }; case_priority_is_distinct_from_ml_risk: true };

const apiBase = import.meta.env.VITE_API_BASE_URL ?? "/api/v1";
const nextStates: Record<CaseStatus, CaseStatus[]> = { OPEN: ["IN_REVIEW"], IN_REVIEW: ["ESCALATED", "CLEARED"], ESCALATED: ["CLOSED"], CLEARED: ["CLOSED"], CLOSED: [] };
const statusCopy: Record<CaseStatus, string> = { OPEN: "Open", IN_REVIEW: "In review", ESCALATED: "Escalated", CLEARED: "Cleared", CLOSED: "Closed" };
const actionCopy: Record<CaseStatus, string> = { OPEN: "Open case", IN_REVIEW: "Start review", ESCALATED: "Escalate case", CLEARED: "Clear case", CLOSED: "Close case" };
const dispositionOptions: Disposition[] = ["NONE", "CLEARED", "ESCALATED"];
const dispositionCopy: Record<Disposition, string> = { NONE: "No disposition", CLEARED: "Cleared", SUSPICIOUS: "Suspicious", ESCALATED: "Escalated" };

function formatAmount(value: number | null | undefined) { return value == null ? "—" : value.toLocaleString(undefined, { maximumFractionDigits: 2 }); }
function readable(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase()); }
function formatDate(value: string) { return new Date(value).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }); }
function formatFact(key: string, value: unknown) {
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (typeof value !== "number") return String(value);
  if (["probability", "prevalence", "percentile", "threshold"].some((term) => key.includes(term))) return `${(value * 100).toFixed(2)}%`;
  if (key.includes("ratio")) return `${value.toFixed(2)}×`;
  return value.toLocaleString(undefined, { maximumFractionDigits: 4 });
}

async function requestJson<T>(url: string, init?: RequestInit): Promise<T> {
  let response: Response;
  try { response = await fetch(url, init); } catch { throw new Error("Backend unavailable. Start the API and try again."); }
  let payload: T | ApiError;
  try { payload = await response.json() as T | ApiError; } catch { throw new Error("The backend returned an invalid response. Check API readiness and retry."); }
  if (!response.ok) { const detail = (payload as ApiError).detail; const message = typeof detail === "string" ? detail : Array.isArray(detail) ? detail[0]?.msg : undefined; throw new Error(message ?? `Request failed (${response.status})`); }
  return payload as T;
}

function Icon({ name, size = 18 }: { name: string; size?: number }) {
  const paths: Record<string, ReactNode> = {
    shield: <><path d="M12 3 4.8 6v5.2c0 4.5 3 8.6 7.2 9.8 4.2-1.2 7.2-5.3 7.2-9.8V6L12 3Z"/><path d="m9 12 2 2 4-4"/></>, plus: <><path d="M12 5v14M5 12h14"/></>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, refresh: <><path d="M20 6v5h-5"/><path d="M18.5 15a7 7 0 1 1-1-8.5L20 9"/></>, queue: <><rect x="4" y="4" width="16" height="16" rx="3"/><path d="M8 9h8M8 13h8M8 17h5"/></>, model: <><path d="M5 5h14v14H5z"/><path d="M9 9h6v6H9zM9 2v3M15 2v3M9 19v3M15 19v3M2 9h3M19 9h3M2 15h3M19 15h3"/></>, evidence: <><path d="M9 4h6l1 2h3v15H5V6h3l1-2Z"/><path d="M9 12h6M9 16h4"/></>, history: <><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/></>, sparkle: <><path d="m12 3 1.2 4.2L17 9l-3.8 1.8L12 15l-1.2-4.2L7 9l3.8-1.8L12 3Z"/><path d="m18 15 .7 2.3L21 18l-2.3.7L18 21l-.7-2.3L15 18l2.3-.7L18 15Z"/></>, user: <><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>, lock: <><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>, note: <><path d="M5 3h14v18H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></>, check: <path d="m5 12 4 4L19 6"/>, alert: <><path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v4M12 17h.01"/></>, chevron: <path d="m9 18 6-6-6-6"/>, filter: <path d="M4 6h16M7 12h10M10 18h4"/>,
  };
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function Badge({ kind, value, label }: { kind: "risk" | "priority" | "status" | "disposition"; value: string; label?: string }) { return <span className={`badge badge-${kind} badge-${kind}-${value.toLowerCase().replaceAll("_", "-")}`}><span className="badge-dot"/>{label ?? readable(value)}</span>; }

function App() {
  const [cases, setCases] = useState<CaseSummary[]>([]); const [total, setTotal] = useState(0); const [selected, setSelected] = useState<CaseDetail | null>(null);
  const [reference, setReference] = useState("TX-000000001"); const [statusFilter, setStatusFilter] = useState(""); const [riskFilter, setRiskFilter] = useState(""); const [priorityFilter, setPriorityFilter] = useState(""); const [dispositionFilter, setDispositionFilter] = useState("");
  const [note, setNote] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const [readiness, setReadiness] = useState<SystemReadiness | null>(null); const [readinessError, setReadinessError] = useState(false); const [queueLoading, setQueueLoading] = useState(true);
  const [operationalMetrics, setOperationalMetrics] = useState<OperationalMetrics | null>(null); const [metricsError, setMetricsError] = useState(false);
  const query = useMemo(() => { const params = new URLSearchParams({ limit: "50", offset: "0" }); if (statusFilter) params.set("status", statusFilter); if (riskFilter) params.set("risk_level", riskFilter); if (priorityFilter) params.set("priority", priorityFilter); if (dispositionFilter) params.set("disposition", dispositionFilter); return params.toString(); }, [statusFilter, riskFilter, priorityFilter, dispositionFilter]);
  const activeFilters = [statusFilter, riskFilter, priorityFilter, dispositionFilter].filter(Boolean);
  const loadReadiness = useCallback(async () => { try { setReadiness(await requestJson<SystemReadiness>(`${apiBase}/system/readiness`)); setReadinessError(false); } catch { setReadinessError(true); } }, []);
  const loadMetrics = useCallback(async () => { try { setOperationalMetrics(await requestJson<OperationalMetrics>(`${apiBase}/system/metrics`)); setMetricsError(false); } catch { setMetricsError(true); } }, []);
  const loadDetail = useCallback(async (caseId: string) => { setBusy("detail"); setError(null); try { setSelected(await requestJson<CaseDetail>(`${apiBase}/cases/${caseId}`)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Case could not be loaded"); } finally { setBusy(null); } }, []);
  const loadQueue = useCallback(async (preferredCaseId?: string) => { setQueueLoading(true); setError(null); try { const payload = await requestJson<CaseList>(`${apiBase}/cases?${query}`); setCases(payload.items); setTotal(payload.total); const nextId = preferredCaseId ?? (payload.items.some((item) => item.case_id === selected?.case.case_id) ? selected?.case.case_id : payload.items[0]?.case_id); if (nextId) await loadDetail(nextId); else setSelected(null); } catch (caught) { setCases([]); setTotal(0); setSelected(null); setError(caught instanceof Error ? caught.message : "Case queue unavailable"); } finally { setQueueLoading(false); void loadReadiness(); void loadMetrics(); } }, [loadDetail, loadMetrics, loadReadiness, query, selected?.case.case_id]);
  useEffect(() => { void loadQueue(); }, [query]);
  useEffect(() => { void loadReadiness(); }, [loadReadiness]);
  useEffect(() => { void loadMetrics(); }, [loadMetrics]);

  async function createCase(event: React.FormEvent) { event.preventDefault(); setBusy("create"); setError(null); try { const detail = await requestJson<CaseDetail>(`${apiBase}/cases`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transaction_reference: reference.trim() }) }); setSelected(detail); await loadQueue(detail.case.case_id); } catch (caught) { setError(caught instanceof Error ? caught.message : "Case could not be created"); } finally { setBusy(null); } }
  async function updateCase(status?: CaseStatus) { if (!selected) return; if (!status && !note.trim()) { setError("Enter an analyst note before saving."); return; } setBusy(status ?? "note"); setError(null); try { const body: { status?: CaseStatus; analyst_note?: string } = {}; if (status) body.status = status; if (note.trim()) body.analyst_note = note.trim(); const detail = await requestJson<CaseDetail>(`${apiBase}/cases/${selected.case.case_id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setSelected(detail); setNote(""); await loadQueue(detail.case.case_id); } catch (caught) { setError(caught instanceof Error ? caught.message : "Case could not be updated"); } finally { setBusy(null); } }
  async function generateCopilot() { if (!selected) return; setBusy("copilot"); setError(null); try { await requestJson<Copilot>(`${apiBase}/cases/${selected.case.case_id}/copilot`, { method: "POST" }); await loadDetail(selected.case.case_id); } catch (caught) { setError(caught instanceof Error ? caught.message : "Copilot unavailable"); } finally { setBusy(null); } }
  function clearFilters() { setStatusFilter(""); setRiskFilter(""); setPriorityFilter(""); setDispositionFilter(""); }
  const snapshot = selected?.intelligence_snapshot; const caseIsClosed = selected?.case.status === "CLOSED";

  return <main className="app-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="Fraudetect AI analyst workspace"><span className="brand-mark"><Icon name="shield" size={20}/></span><span><b>Fraudetect</b><small>AI</small></span></a><div className="topbar-context"><span className="live-dot"/><span>Analyst workspace</span><em>Human decisions stay authoritative</em></div></header>
    <section className="hero" aria-labelledby="page-title"><div className="hero-copy"><p className="eyebrow">Fraud investigation operations</p><h1 id="page-title">Turn risk signals into <span>clear decisions.</span></h1><p>Review explainable model output, historical intelligence, and grounded evidence in one traceable analyst workflow.</p></div><form className="create-card" onSubmit={createCase}><span className="create-icon"><Icon name="plus" size={20}/></span><div><p className="eyebrow">Start an investigation</p><h2>Create a case</h2></div><label htmlFor="reference">Prepared transaction reference</label><div className="input-action"><input id="reference" value={reference} onChange={(event) => setReference(event.target.value)} required maxLength={64} pattern="[A-Za-z0-9][A-Za-z0-9._:-]*" placeholder="e.g. TX-000000001"/><button className="button button-primary" disabled={busy === "create"}>{busy === "create" ? <><span className="spinner"/>Creating</> : <>Create case<Icon name="arrow" size={17}/></>}</button></div><small>Resolved securely by the backend. The reference is never stored in the case.</small></form></section>
    <section className="workflow" aria-label="Investigation workflow">{[["01", "model", "Predict & investigate", "Score risk and capture evidence"], ["02", "plus", "Create a case", "Freeze the intelligence snapshot"], ["03", "evidence", "Review intelligence", "Understand signals and history"], ["04", "sparkle", "Document & decide", "Add notes, Copilot, escalate or clear"], ["05", "lock", "Close the case", "Preserve the final audit trail"]].map(([number, icon, title, detail], index) => <div className="workflow-step" key={number}><span className="step-number">{number}</span><span className="step-icon"><Icon name={icon}/></span><span><strong>{title}</strong><small>{detail}</small></span>{index < 4 ? <Icon name="chevron" size={15}/> : null}</div>)}</section>
    <SystemStatus readiness={readiness} unavailable={readinessError} onRefresh={() => void loadReadiness()}/>
    <OperationalOverview metrics={operationalMetrics} unavailable={metricsError} onRefresh={() => void loadMetrics()}/>
    {error ? <div className="error-banner" role="alert"><Icon name="alert" size={20}/><div><strong>Action could not be completed</strong><span>{error}</span></div><button onClick={() => setError(null)} aria-label="Dismiss notification">×</button></div> : null}
    <section className="workspace" aria-label="Analyst investigation workspace"><aside className="queue-panel">
      <div className="queue-heading"><div className="title-with-icon"><span><Icon name="queue"/></span><div><p className="eyebrow">Investigation queue</p><h2>{queueLoading ? "Loading cases…" : `${total} ${total === 1 ? "case" : "cases"}`}</h2></div></div><button className="icon-button" onClick={() => void loadQueue()} disabled={queueLoading} aria-label="Refresh case queue" title="Refresh case queue"><Icon name="refresh"/></button></div>
      <div className="filter-header"><span><Icon name="filter" size={16}/>Filter cases</span>{activeFilters.length ? <button onClick={clearFilters}>Reset all</button> : null}</div><div className="filters"><label>Investigation status<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">Any status</option>{Object.keys(nextStates).map((value) => <option key={value} value={value}>{statusCopy[value as CaseStatus]}</option>)}</select></label><label>ML risk level<select value={riskFilter} onChange={(event) => setRiskFilter(event.target.value)}><option value="">Any risk</option>{["HIGH", "MEDIUM", "LOW"].map((value) => <option key={value} value={value}>{readable(value)}</option>)}</select></label><label>Workflow priority<select value={priorityFilter} onChange={(event) => setPriorityFilter(event.target.value)}><option value="">Any priority</option>{["CRITICAL", "HIGH", "MEDIUM", "LOW"].map((value) => <option key={value} value={value}>{readable(value)}</option>)}</select></label><label>Analyst disposition<select value={dispositionFilter} onChange={(event) => setDispositionFilter(event.target.value)}><option value="">Any disposition</option>{dispositionOptions.map((value) => <option key={value} value={value}>{dispositionCopy[value]}</option>)}</select></label></div>{activeFilters.length ? <div className="filter-summary"><span>{activeFilters.length}</span> active filter{activeFilters.length === 1 ? "" : "s"}</div> : null}
      <div className="case-list">{queueLoading ? <EmptyState loading title="Loading investigations" detail="Reading safe workflow summaries…"/> : !cases.length ? <EmptyState title={activeFilters.length ? "No matching cases" : "No investigations yet"} detail={activeFilters.length ? "Reset or adjust the filters above." : "Create a case from a prepared reference to begin."}/> : cases.map((item) => <button key={item.case_id} className={`case-row ${selected?.case.case_id === item.case_id ? "active" : ""}`} onClick={() => void loadDetail(item.case_id)} aria-pressed={selected?.case.case_id === item.case_id}><div className="case-row-top"><Badge kind="priority" value={item.priority} label={`${readable(item.priority)} priority`}/><Badge kind="status" value={item.status}/></div><strong className="case-id">{item.case_id}</strong><div className="case-risk"><span className={`risk-orb risk-${item.risk_level.toLowerCase()}`}/><span><strong>{item.risk_level} ML risk</strong><small>{(item.fraud_probability * 100).toFixed(1)}% probability</small></span></div><div className="case-meta"><span>{item.evidence_summary.total_count} evidence signals</span><time>{formatDate(item.created_at)}</time></div></button>)}</div>
    </aside><section className="detail-panel" aria-live="polite">{!selected ? <div className="detail-empty"><span><Icon name={busy === "detail" ? "refresh" : "queue"} size={28}/></span><p className="eyebrow">{busy === "detail" ? "Loading investigation" : "No case selected"}</p><h2>Choose a case to begin reviewing</h2><p>The case snapshot preserves exactly what was known when the investigation was created.</p></div> : <>
      <header className="case-header"><div><p className="eyebrow"><Icon name="lock" size={14}/>Immutable investigation snapshot</p><h2>{selected.case.case_id}</h2><p>Created {formatDate(selected.case.created_at)} · {readable(selected.case.source_type)} input</p></div><div className="case-header-actions"><Badge kind="priority" value={selected.case.priority} label={`${readable(selected.case.priority)} workflow priority`}/><Badge kind="status" value={selected.case.status}/></div></header>
      <section className="concept-strip" aria-label="Case classifications"><article><span className="concept-icon concept-risk"><Icon name="model"/></span><div><small>ML risk</small><strong>{readable(selected.case.risk_level)}</strong><p>Frozen model assessment</p></div></article><article><span className="concept-icon concept-priority"><Icon name="alert"/></span><div><small>Case priority</small><strong>{readable(selected.case.priority)}</strong><p>Orders analyst workload</p></div></article><article><span className="concept-icon concept-status"><Icon name="history"/></span><div><small>Investigation status</small><strong>{statusCopy[selected.case.status]}</strong><p>Where the case is now</p></div></article><article><span className="concept-icon concept-disposition"><Icon name="user"/></span><div><small>Analyst disposition</small><strong>{readable(selected.case.analyst_decision.disposition)}</strong><p>Human judgment only</p></div></article></section>
      <section className="section-card assessment-card"><SectionHeader icon="model" eyebrow="Frozen model output" title="ML risk assessment" helper="Captured at case creation · cannot be changed by analyst actions"/><div className="assessment-content"><div className={`score-ring score-${selected.case.risk_level.toLowerCase()}`} style={{ "--score": snapshot?.model_output.risk_score ?? 0 } as CSSProperties}><div><strong>{snapshot?.model_output.risk_score.toFixed(1)}</strong><span>Risk score</span></div></div><div className="assessment-summary"><Badge kind="risk" value={selected.case.risk_level} label={`${selected.case.risk_level} ML risk`}/><h3>{(selected.case.fraud_probability * 100).toFixed(2)}% fraud probability</h3><p>{snapshot?.model_output.fraud_prediction ? "The score is above" : "The score remains below"} the active {((snapshot?.model_output.classification_threshold ?? 0) * 100).toFixed(2)}% decision threshold.</p></div><dl className="model-facts"><div><dt>Model version</dt><dd>{selected.case.model_version}</dd></div><div><dt>Operating mode</dt><dd>{readable(selected.case.operating_mode)}</dd></div><div><dt>Simulated action</dt><dd>{readable(snapshot?.model_output.recommended_simulated_action ?? "")}</dd></div><div><dt>Prediction</dt><dd>{snapshot?.model_output.fraud_prediction ? "Positive" : "Negative"}</dd></div></dl></div><div className="transaction-context"><div><span>Transaction type</span><strong>{readable(snapshot?.transaction.transaction_type ?? "")}</strong></div><div><span>Amount</span><strong>{formatAmount(snapshot?.transaction.amount)}</strong></div><div><span>Origin balance before</span><strong>{formatAmount(snapshot?.transaction.origin_balance_before)}</strong></div><div><span>Hour of day</span><strong>{snapshot?.transaction.hour_of_day ?? "—"}:00</strong></div></div></section>
      <InvestigationSummary detail={selected}/>
      <section className="section-card evidence-card"><SectionHeader icon="evidence" eyebrow="Evidence & intelligence" title={`${selected.case.evidence_summary.total_count} deterministic signals`} helper="Recorded facts and comparisons—not causal claims"/><div className="evidence-grid">{snapshot?.evidence.map((item) => <article key={item.evidence_id} className={`evidence evidence-${item.severity.toLowerCase()}`}><div className="evidence-top"><Badge kind="risk" value={item.severity} label={readable(item.severity)}/><code>{item.evidence_id}</code></div><h4>{item.title}</h4><dl>{Object.entries(item.facts).slice(0, 3).map(([key, value]) => <div key={key}><dt>{readable(key)}</dt><dd>{formatFact(key, value)}</dd></div>)}</dl></article>)}</div></section>
      <div className="intelligence-grid"><IntelligenceCard icon="history" title="Behavioral intelligence" heading={snapshot?.behavioral_context.history_available ? "Prior activity available" : "No prior activity available"} description="Compares this transaction only with earlier activity from the same origin." values={[["Prior transactions", snapshot?.behavioral_context.prior_transaction_count ?? 0], ["Prior average", formatAmount(snapshot?.behavioral_context.prior_amount?.average)], ["Amount vs average", `${snapshot?.behavioral_context.current_amount_context?.amount_vs_prior_average?.toFixed(2) ?? "—"}×`], ["Historical percentile", snapshot?.behavioral_context.current_amount_context ? `${(snapshot.behavioral_context.current_amount_context.prior_empirical_percentile * 100).toFixed(0)}%` : "—"]]} note={snapshot?.behavioral_context.availability_explanation ?? ""}/><IntelligenceCard icon="evidence" title="Relationship intelligence" heading={snapshot?.relationship_context.relationship_seen_before ? "Previously observed pair" : snapshot?.relationship_context.context_available ? "First observed pair" : "Relationship context unavailable"} description="Reviews only earlier interactions between the origin, destination, and their networks." values={[["Prior interactions", snapshot?.relationship_context.prior_interaction_count ?? 0], ["Pair average", formatAmount(snapshot?.relationship_context.prior_amount?.average)], ["Origin network", snapshot?.relationship_context.origin_network.prior_unique_counterparty_count ?? 0], ["Destination network", snapshot?.relationship_context.destination_network.prior_unique_origin_count ?? 0]]} note={snapshot?.relationship_context.availability_explanation ?? ""}/></div>
      <section className="section-card copilot-card"><div className="section-heading"><SectionTitle icon="sparkle" eyebrow="Investigation Copilot" title={selected.copilot ? "Grounded analyst brief" : "Generate an advisory brief"}/><button className="button button-copilot" onClick={() => void generateCopilot()} disabled={busy === "copilot" || caseIsClosed}>{caseIsClosed ? <><Icon name="lock"/>Case closed</> : busy === "copilot" ? <><span className="spinner"/>Generating brief</> : <><Icon name="sparkle"/>{selected.copilot ? "Regenerate brief" : "Generate brief"}</>}</button></div>{!selected.copilot ? <div className="copilot-empty"><p>Copilot summarizes only the stored, identifier-free investigation snapshot. It is advisory and cannot change model output, priority, status, or analyst decisions.</p><span><Icon name="shield" size={16}/>A deterministic fallback is available without an API key.</span></div> : <CopilotReport copilot={selected.copilot}/>}</section>
      <section className="section-card decision-card"><div className="section-heading"><SectionTitle icon="user" eyebrow="Analyst decision" title="Review, document, and resolve"/><div className="authority-label"><Icon name="shield" size={15}/><span><strong>Human authoritative</strong><small>Never model ground truth</small></span></div></div><div className="decision-status"><div><span>Current status</span><Badge kind="status" value={selected.case.status}/></div><div><span>Current disposition</span><Badge kind="disposition" value={selected.case.analyst_decision.disposition}/></div></div>{caseIsClosed ? <div className="closed-notice"><Icon name="lock"/><div><strong>This case is closed and immutable</strong><p>Notes, Copilot reports, and lifecycle fields can no longer be changed.</p></div></div> : <><label htmlFor="note">Analyst note <span>Optional when changing status</span><textarea id="note" value={note} onChange={(event) => setNote(event.target.value)} maxLength={2000} placeholder="Record your rationale, checks performed, or handoff context…"/></label><div className="decision-actions"><button className="button button-secondary" onClick={() => void updateCase()} disabled={!note.trim() || busy !== null}><Icon name="note"/>{busy === "note" ? "Saving note…" : "Save note only"}</button><div className="lifecycle-actions"><span>Available next step{nextStates[selected.case.status].length === 1 ? "" : "s"}</span>{nextStates[selected.case.status].map((state) => <button key={state} className={`button action-${state.toLowerCase()}`} onClick={() => void updateCase(state)} disabled={busy !== null}>{busy === state ? <><span className="spinner"/>Updating</> : <>{state === "ESCALATED" ? <Icon name="alert"/> : state === "CLEARED" ? <Icon name="check"/> : state === "CLOSED" ? <Icon name="lock"/> : <Icon name="arrow"/>}{actionCopy[state]}</>}</button>)}</div></div></>}{selected.case.analyst_decision.note ? <blockquote><span><Icon name="note" size={16}/>Latest analyst note</span><p>{selected.case.analyst_decision.note}</p></blockquote> : null}</section>
      <section className="section-card trace-card"><SectionHeader icon="history" eyebrow="Decision trace" title="Append-only case timeline" helper="Every item below is a stored event; no timestamps are inferred"/><div className="timeline">{selected.decision_trace.map((item, index) => <div key={`${item.event}-${item.occurred_at}-${index}`} className={`trace-event trace-${item.actor.toLowerCase()}`}><span className="trace-marker"><Icon name={item.actor === "ANALYST" ? "user" : item.actor === "COPILOT" ? "sparkle" : "shield"} size={14}/></span><time>{formatDate(item.occurred_at)}</time><div><span className="actor-label">{readable(item.actor)}</span><strong>{item.label}</strong><p>{item.detail}{item.previous_status && item.new_status ? ` ${statusCopy[item.previous_status]} → ${statusCopy[item.new_status]}.` : ""}{item.copilot_mode ? ` Mode: ${readable(item.copilot_mode)}.` : ""}</p></div></div>)}</div></section>
      <section className="limitations"><span><Icon name="alert"/></span><div><strong>Investigation limitations</strong><p>Keep these constraints in mind before making a decision.</p><ul>{selected.investigation_limitations.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    </>}</section></section>
    <footer><span><Icon name="shield" size={15}/>Fraudetect AI</span><span>Local demonstration · No autonomous payment actions · Identifiers excluded from case storage</span></footer>
  </main>;
}

function SectionTitle({ icon, eyebrow, title }: { icon: string; eyebrow: string; title: string }) { return <div className="title-with-icon"><span><Icon name={icon}/></span><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div></div>; }
function SectionHeader({ icon, eyebrow, title, helper }: { icon: string; eyebrow: string; title: string; helper: string }) { return <div className="section-heading"><SectionTitle icon={icon} eyebrow={eyebrow} title={title}/><p className="section-helper">{helper}</p></div>; }
function EmptyState({ title, detail, loading = false }: { title: string; detail: string; loading?: boolean }) { return <div className="empty-state"><span className={loading ? "loading-icon" : ""}><Icon name={loading ? "refresh" : "queue"} size={24}/></span><strong>{title}</strong><p>{detail}</p></div>; }

function InvestigationSummary({ detail }: { detail: CaseDetail }) {
  const { intelligence_snapshot: snapshot } = detail;
  const severityRank: Record<Evidence["severity"], number> = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3, INFO: 4 };
  const keySignals = snapshot.evidence
    .map((item, index) => ({ item, index }))
    .sort((left, right) => severityRank[left.item.severity] - severityRank[right.item.severity] || left.index - right.index)
    .slice(0, 4)
    .map(({ item }) => item);
  const topSignal = keySignals[0];
  const probability = `${(detail.case.fraud_probability * 100).toFixed(2)}%`;
  const threshold = `${(snapshot.model_output.classification_threshold * 100).toFixed(2)}%`;
  const behavior = snapshot.behavioral_context;
  const relationship = snapshot.relationship_context;
  const behaviorContext = behavior.history_available
    ? `${behavior.prior_transaction_count} strictly prior transaction${behavior.prior_transaction_count === 1 ? " is" : "s are"} available for behavioral comparison.`
    : `Behavioral history unavailable: ${behavior.availability_explanation}`;
  const relationshipContext = !relationship.context_available
    ? `Relationship context unavailable: ${relationship.availability_explanation}`
    : relationship.history_available
      ? `${relationship.prior_interaction_count} strictly prior interaction${relationship.prior_interaction_count === 1 ? " is" : "s are"} available for relationship comparison.`
      : `No prior direct pair was observed. Earlier network context records ${relationship.origin_network.prior_unique_counterparty_count} origin counterpart${relationship.origin_network.prior_unique_counterparty_count === 1 ? "y" : "ies"} and ${relationship.destination_network.prior_unique_origin_count} destination origin${relationship.destination_network.prior_unique_origin_count === 1 ? "" : "s"}.`;
  const focusPoints = [
    topSignal ? `Review the recorded facts supporting “${topSignal.title}” before choosing a disposition.` : "No deterministic evidence signals were recorded; avoid inferring unsupported risk drivers.",
    behavior.history_available ? `Use the recorded ${behavior.prior_transaction_count}-transaction behavioral baseline when checking whether the current activity is unusual.` : "Treat the behavioral baseline as unavailable; do not infer prior behavior.",
    !relationship.context_available
      ? "Treat relationship context as unavailable; do not infer an earlier connection."
      : relationship.history_available
        ? `Review the recorded ${relationship.prior_interaction_count}-interaction relationship baseline for relevant context.`
        : "Review the first-observed pair and recorded network context; do not infer a prior direct relationship.",
  ];

  return <section className="section-card investigation-summary" aria-label="Investigation summary">
    <div className="summary-heading"><SectionTitle icon="shield" eyebrow="Investigation summary" title="What matters at a glance"/><span className="system-generated-label"><Icon name="check" size={14}/>Deterministic system summary · Not LLM-generated</span></div>
    <div className="summary-risk"><div><span>Current ML risk</span><Badge kind="risk" value={detail.case.risk_level} label={`${detail.case.risk_level} ML risk`}/></div><div><span>Fraud probability</span><strong>{probability}</strong></div><div><span>Workflow priority</span><Badge kind="priority" value={detail.case.priority} label={`${readable(detail.case.priority)} priority`}/></div></div>
    <div className="summary-grid">
      <article className="summary-why"><h4>Why this case needs attention</h4><p>The frozen model assigns <strong>{readable(detail.case.risk_level)} ML risk</strong> at <strong>{probability}</strong>, {snapshot.model_output.fraud_prediction ? "above" : "below"} the active {threshold} threshold. {topSignal ? <>The highest-ranked recorded signal is <strong>“{topSignal.title}”</strong> ({readable(topSignal.severity)}).</> : <>No deterministic evidence signals were recorded.</>}</p><small>Workflow priority orders analyst review only; it is not a new ML risk level.</small></article>
      <article className="summary-signals"><h4>Key signals</h4>{keySignals.length ? <ul>{keySignals.map((signal) => <li key={signal.evidence_id}><Badge kind="risk" value={signal.severity} label={readable(signal.severity)}/><span>{signal.title}</span></li>)}</ul> : <p>No deterministic evidence signals are available in this snapshot.</p>}</article>
      <article className="summary-context"><h4>Context</h4><p><Icon name="history" size={14}/><span><strong>Behavioral</strong>{behaviorContext}</span></p><p><Icon name="evidence" size={14}/><span><strong>Relationship</strong>{relationshipContext}</span></p>{detail.investigation_limitations[0] ? <p className="summary-limitation"><Icon name="alert" size={14}/><span><strong>Recorded limitation</strong>{detail.investigation_limitations[0]}</span></p> : null}</article>
      <article className="summary-focus"><h4>Analyst focus</h4><ul>{focusPoints.map((point) => <li key={point}>{point}</li>)}</ul><small>Advisory only · The human analyst remains authoritative.</small></article>
    </div>
  </section>;
}

function IntelligenceCard({ icon, title, heading, description, values, note }: { icon: string; title: string; heading: string; description: string; values: [string, string | number][]; note: string }) { return <section className="section-card intelligence-card"><SectionTitle icon={icon} eyebrow={title} title={heading}/><p className="intelligence-description">{description}</p><div className="intelligence-metrics">{values.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="context-note"><Icon name="history" size={15}/>{note}</p></section>; }

function SystemStatus({ readiness, unavailable, onRefresh }: { readiness: SystemReadiness | null; unavailable: boolean; onRefresh: () => void }) {
  if (unavailable) return <section className="system-status system-unavailable"><div><span className="status-icon"><Icon name="alert"/></span><div><strong>System readiness unavailable</strong><p>Start the backend to inspect components. Case data has not been changed.</p></div></div><button className="button button-ghost" onClick={onRefresh}><Icon name="refresh"/>Retry</button></section>;
  if (!readiness) return <section className="system-status"><div><span className="status-icon loading-icon"><Icon name="refresh"/></span><div><strong>Checking system readiness</strong><p>Confirming local investigation components…</p></div></div></section>;
  const readyCount = readiness.components.filter((item) => item.status === "ready").length;
  return <details className={`system-status system-${readiness.status}`}><summary><div><span className="status-icon"><Icon name={readiness.status === "ready" ? "check" : "alert"}/></span><div><strong>{readiness.status === "ready" ? "Investigation workspace is ready" : "Workspace is partially available"}</strong><p>{readyCount} of {readiness.components.length} components ready · External providers are not contacted by this check</p></div></div><span className="details-action">View components<Icon name="chevron" size={15}/></span></summary><div className="component-grid">{readiness.components.map((item) => <article key={item.key}><span className={`component-state state-${item.status}`}><span/>{readable(item.status)}</span><strong>{item.label}</strong><small>{item.mode ? readable(item.mode) : item.version ?? "Local component"}</small><p>{item.message}</p>{item.fallback_available ? <em>Fallback available</em> : null}</article>)}</div><button className="button button-ghost status-refresh" onClick={onRefresh}><Icon name="refresh"/>Refresh readiness</button></details>;
}

function OperationalOverview({ metrics, unavailable, onRefresh }: { metrics: OperationalMetrics | null; unavailable: boolean; onRefresh: () => void }) {
  if (unavailable) return <section className="overview-card overview-unavailable"><div><p className="eyebrow">Operations overview</p><h2>Workflow metrics unavailable</h2></div><button className="button button-ghost" onClick={onRefresh}><Icon name="refresh"/>Retry</button></section>;
  if (!metrics) return <section className="overview-card overview-loading"><span className="loading-icon"><Icon name="refresh"/></span><strong>Loading investigation overview…</strong></section>;
  const priorities: [string, number][] = [["CRITICAL", metrics.priority_counts.critical], ["HIGH", metrics.priority_counts.high], ["MEDIUM", metrics.priority_counts.medium], ["LOW", metrics.priority_counts.low]];
  const cards: [string, number, string, string][] = [["Total cases", metrics.total_cases, "All stored investigations", "queue"], ["Active workload", metrics.active_cases, `${metrics.status_counts.open} open · ${metrics.status_counts.in_review} in review`, "history"], ["Escalated", metrics.status_counts.escalated, "Awaiting further action", "alert"], ["Cleared", metrics.status_counts.cleared, "Resolved by an analyst", "check"], ["Closed", metrics.status_counts.closed, "Completed and immutable", "lock"], ["Copilot briefs", metrics.copilot_reports.total, `${metrics.copilot_reports.real_llm} real LLM · ${metrics.copilot_reports.deterministic_fallback} fallback`, "sparkle"]];
  return <section className="overview-card"><div className="overview-heading"><div><p className="eyebrow">Operations overview</p><h2>Investigation dashboard</h2><p>Live counts from stored workflow data—not model performance metrics.</p></div><button className="button button-ghost" onClick={onRefresh}><Icon name="refresh"/>Refresh</button></div><div className="overview-grid">{cards.map(([label, value, detail, icon]) => <article key={label}><span className="metric-icon"><Icon name={icon}/></span><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>)}</div><div className="priority-overview"><div><strong>Workflow priority</strong><small>Orders the analyst queue; it is separate from ML risk.</small></div><div>{priorities.map(([priority, count]) => <Badge key={priority} kind="priority" value={priority} label={`${readable(priority)} ${count}`}/>)}</div></div></section>;
}

function CopilotReport({ copilot }: { copilot: Copilot }) {
  const latency = copilot.execution?.generation_latency_ms; const isReal = copilot.mode === "real_llm";
  return <div className="copilot-report"><div className={`copilot-mode mode-${isReal ? "real" : "fallback"}`}><span className="mode-icon"><Icon name={isReal ? "sparkle" : "shield"}/></span><div><strong>{isReal ? "Real LLM advisory" : "Deterministic fallback"}</strong><p>{isReal ? "Provider-generated and locally validated" : "Not LLM-generated · rules-based and reproducible"}</p></div><div className="mode-meta"><span>{readable(copilot.provider)}</span>{copilot.model ? <span>{copilot.model}</span> : null}{latency != null ? <span>{latency} ms local elapsed</span> : null}</div></div>{copilot.mode === "deterministic_fallback" && copilot.execution?.failure_category ? <p className="fallback-reason">Fallback reason: <strong>{readable(copilot.execution.failure_category)}</strong></p> : null}<p className="report-summary">{copilot.report.summary}</p><div className="report-columns"><div><h4>Key grounded signals</h4>{copilot.report.key_signals.map((signal) => <article key={`${signal.signal}-${signal.evidence_ids.join("-")}`}><span className="signal-importance">{readable(signal.importance)}</span><strong>{signal.signal}</strong><p>{signal.explanation}</p><code>{signal.evidence_ids.join(" · ")}</code></article>)}</div><div><h4>Recommended analyst actions</h4><ol>{copilot.report.recommended_actions.map((item, index) => <li key={item.action}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{item.action}</strong><p>{item.reason}</p></div></li>)}</ol><h4>Known uncertainties</h4><ul>{copilot.report.uncertainties.map((item) => <li key={item}>{item}</li>)}</ul></div></div><p className="disclaimer"><Icon name="alert" size={15}/>{copilot.report.disclaimer}</p></div>;
}

export default App;
